### ISSUE TITLE
Error while attempting to mount volume at /home/mmadu

### ISSUE THREAD

**Issue by yudori** [geraldoyudo/mmadu#120]
Starting up containers (with docker-compose up) causes the following error:

![image](https://user-images.githubusercontent.com/8599235/87244229-be1a6b00-c433-11ea-965c-9897ecd2b39e.png)

OS: MacOS Mojave (10.14.6)

**Comment by geraldoyudo** [comment]
@yudori , I've fixed it, please confirm.
